import { createContext, createElement, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

export const LANGUAGES = {
  es: 'ES',
  en: 'EN',
};

export const TRANSLATIONS = {
  es: {
    nav: {
      home: 'Inicio',
      menu: 'Menu',
      order: 'Ordena',
      catering: 'Catering',
      locations: 'Ubicaciones',
      contact: 'Contacto',
    },
    common: {
      order: 'Ordenar',
      pickup: 'Ordenar Pickup',
      delivery: 'Pedir Delivery',
      viewLocations: 'Ver ubicaciones',
      emailTeam: 'Escribir al equipo',
      directEmail: 'Email directo',
      locations: 'Ubicaciones',
      allDay: 'Todos los dias',
      signature: 'De la casa',
      closePromo: 'Cerrar promocion',
      openMenu: 'Abrir menu',
      closeMenu: 'Cerrar menu',
      previousMonth: 'Mes anterior',
      nextMonth: 'Mes siguiente',
    },
    promo: {
      lead: '5 ubicaciones en San Antonio',
      text: 'Abierto diario {{hours}} · Pickup y delivery',
    },
      hero: {
        eyebrow: 'Los Originales de Monterrey',
        subtitle: 'Pollos Asados',
        copy: 'Pollo al carbon, parrilladas y antojos regios servidos con la intensidad de la brasa. Cinco ubicaciones en San Antonio, listas para pickup o delivery.',
        hoursLabel: 'Todos los dias',
        driveLabel: 'Culebra 1 y Marbach',
        signatureTitle: 'Pollo Entero',
        signatureDesc: '8 piezas con arroz, cebolla asada, chile toreado, limon, tortillas y salsas roja y verde.',
      },
      menu: {
        eyebrow: 'Menu de la Casa',
        title: 'La brasa como protagonista',
        copy: 'Pollo asado al carbon, cortes a la parrilla, parrilladas para compartir y postres caseros con una carta clara y directa.',
        featured: 'Favoritos de la casa',
        dishes: 'platillos',
        official: 'Menu oficial Al Carbon',
        officialShort: 'Menu oficial',
        viewFull: 'Ver menu completo',
        categories: {
        all: 'Destacados',
        chicken: 'Pollo',
        beef: 'Res',
        parrilladas: 'Parrilladas',
        burgers: 'Hamburguesas',
        desserts: 'Postres',
        drinks: 'Bebidas',
        extras: 'Extras',
        papaNortena: 'Papa Nortena',
        cannedSodas: 'Refrescos de Lata',
      },
      badges: {
        mostPopular: 'Mas popular',
        fanFavorite: 'Favorito',
        bestSeller: 'Mas vendido',
        bestValue: 'Mejor valor',
        signature: 'De la casa',
        forTwo: 'Para 2',
        mustTry: 'Imperdible',
      },
      items: {
        1: {
          name: 'Pollo Entero',
          desc: '8 piezas de pollo asado al carbon con arroz, cebolla asada, chile toreado, limon, tortillas de maiz, salsa verde y roja.',
        },
        2: {
          name: 'Medio Pollo',
          desc: '4 piezas de pollo asado al carbon con arroz, cebolla asada, chile toreado, limon, tortillas de maiz, salsa verde y roja.',
        },
        3: {
          name: 'Pollo Entero Solo',
          desc: '8 piezas de pollo asado al carbon, sin sides. Solo el puro pollo.',
        },
        4: {
          name: 'Medio Pollo Solo',
          desc: '4 piezas de pollo asado al carbon, sin sides. Solo el puro pollo.',
        },
        5: {
          name: '1 lb Fajita de Res',
          desc: '1 lb de fajita de res a la parrilla con arroz 12 oz, cebollas y pimientos asados, chile toreado, ensalada, tortillas, limon y salsas.',
        },
        6: {
          name: '1/2 lb Fajita de Res',
          desc: '1/2 lb de fajita de res a la parrilla con arroz 8 oz, cebollas y pimientos asados, chile toreado, ensalada, tortillas, limon y salsas.',
        },
        7: {
          name: '1 lb Costillas',
          desc: '1 lb de short ribs a la parrilla con arroz 12 oz, cebollas y pimientos asados, chile toreado, ensalada, tortillas, limon y salsas.',
        },
        8: {
          name: '1/2 lb Costillas',
          desc: '1/2 lb de short ribs a la parrilla con arroz 8 oz, cebollas y pimientos asados, chile toreado, ensalada, tortillas, limon y salsas.',
        },
        9: {
          name: 'Parrillada Para Dos',
          desc: '1/2 lb de fajita, 1/2 pollo, arroz, frijoles charros, ensalada, chile toreado, salchicha especial, 8 tortillas y salsas. Para 2 personas.',
        },
        10: {
          name: 'Parrillada Familiar',
          desc: '1 lb de fajita, 1 pollo entero, 2 arroces, 2 frijoles charros, 2 ensaladas, 2 chiles toreados, 2 salchichas, 16 tortillas y salsas. Para toda la familia.',
        },
        11: {
          name: 'Hamburguesa Clasica',
          desc: '1/2 lb de carne Angus con queso americano, pickles, mostaza, mayo, lechuga y tomate. Servida con papas Lays Classic.',
        },
        12: {
          name: 'Monterrey Burger',
          desc: '1/2 lb de carne Angus con jamon, queso Monterrey Jack, chile toreado, chipotle, cebolla asada, guacamole, lechuga y tomate. Con chips.',
        },
        13: {
          name: 'Salchiburger',
          desc: '1/2 lb de carne Angus con jamon, salchicha, queso Monterrey Jack, cebolla asada, guacamole, lechuga y tomate. Servida con chips.',
        },
        14: {
          name: 'Pastel Tres Leches',
          desc: 'Clasico pastel de tres leches esponjoso y cremoso, cubierto con crema batida.',
        },
        15: {
          name: 'Arroz con Leche',
          desc: 'Cremoso arroz con leche con canela. Un postre casero y reconfortante.',
        },
        16: {
          name: 'Bebida 32 oz',
          desc: 'Bebida de 32 oz a tu eleccion: refrescos, agua de limon o aguas frescas.',
        },
        17: {
          name: 'Bebida 16 oz',
          desc: 'Bebida de 16 oz a tu eleccion: refrescos, agua de limon o aguas frescas.',
        },
        18: {
          name: 'Papa Nortena',
          desc: 'Papa al horno cargada con crema, mantequilla, salsa de queso Monterrey Jack y cheddar, tocino, carne asada, galletas saladas y jalapenos.',
        },
        19: {
          name: 'Frijoles Charros 12 oz',
          desc: 'Frijoles charros caseros, ricos y caldosos. El acompanamiento perfecto para tu plato.',
        },
        20: {
          name: 'Frijoles Charros 32 oz',
          desc: 'Frijoles charros en tamano familiar, ideal para compartir con toda la mesa.',
        },
        21: {
          name: 'Salchicha Asada',
          desc: 'Salchicha especial asada al carbon. El toque extra autentico que completa cualquier plato.',
        },
        22: {
          name: 'Chocoflan',
          desc: 'Irresistible combinacion de pastel de chocolate y flan de vainilla. Cremoso, humedo y lleno de sabor.',
        },
        23: {
          name: 'Flan de Queso',
          desc: 'Suave flan de queso crema banado en caramelo. Textura cremosa y sabor dulce e irresistible.',
        },
        24: {
          name: 'Cheesecake de Fresa',
          desc: 'Cheesecake clasico con base de galleta, relleno cremoso y cobertura de fresas frescas.',
        },
        25: {
          name: 'Refresco 12 oz',
          desc: 'Lata de refresco de 12 oz: Coke, Sprite, Dr Pepper y mas. El complemento perfecto para tu plato.',
        },
      },
    },
    liveMenu: {
      eyebrow: 'Menu en vivo',
      title: 'Menu por sucursal',
      copy: 'Platillos y precios sincronizados directo del sistema de cada sucursal. Elige tu punto y revisa lo que hay hoy.',
      branch: 'Sucursal',
      orderNow: 'Ordenar ahora',
      error: 'No pudimos cargar el menu de esta sucursal. Intenta de nuevo.',
      retry: 'Reintentar',
      synced: 'Precios sincronizados en vivo con cada sucursal',
    },
    cart: {
      title: 'Tu orden',
      add: 'Agregar',
      options: 'Con opciones',
      item: 'articulo',
      items: 'articulos',
      view: 'Ver orden',
      empty: 'Tu orden esta vacia.',
      subtotal: 'Subtotal',
      taxNote: 'Impuestos y propina se calculan al pagar.',
      name: 'Nombre completo',
      email: 'Email',
      phone: 'Telefono (opcional)',
      checkout: 'Pagar con Clover',
      processing: 'Conectando con Clover...',
      error: 'No se pudo iniciar el pago. Intenta de nuevo.',
      emailInvalid: 'Revisa tu email — parece incompleto o invalido.',
      customize: 'Elegir opciones',
      addToOrder: 'Agregar a la orden',
      chooseOne: 'Elige 1',
      chooseAtLeast: 'Elige al menos {{n}}',
      chooseUpTo: 'Elige hasta {{n}}',
      optional: 'Opcional',
      secure: 'Pago seguro procesado por Clover.',
    },
    cateringCta: {
      eyebrow: 'Catering Al Carbon',
      title: 'Lleva la brasa a tu evento.',
      copy: 'Reuniones familiares, oficinas, celebraciones y eventos grandes con el sabor regio de Al Carbon, coordinado desde nuestras sucursales de San Antonio.',
      quote: 'Cotizar catering',
      ideal: 'Ideal para',
      points: ['Parrilladas para grupos', 'Pollo al carbon por volumen', 'Sides, salsas y tortillas'],
      note: 'Completa la solicitud y el equipo recibe todos los detalles del evento en el correo oficial del sitio.',
    },
    catering: {
      title: 'Catering Al Carbon | Eventos y Parrilladas en San Antonio',
      meta: 'Catering de Al Carbon Pollos Asados para eventos en San Antonio. Solicita pollo al carbon, parrilladas, fajita, sides y coordinacion para grupos.',
      heroEyebrow: 'Solicitud de catering',
      heroSubtitle: 'Al Carbon',
      heroCopy: 'Planeas un evento? Nosotros nos encargamos de la comida con pollo al carbon, parrilladas, fajita, sides y el sabor de brasa que San Antonio ya conoce.',
      heroAlt: 'Parrillada familiar Al Carbon para catering',
      quote: 'Solicitar cotizacion',
      statsEyebrow: 'Eventos con fuego real',
      branches: 'Sucursales',
      daily: 'Diario',
      fire: 'Brasa',
      regional: 'Regia',
      introEyebrow: 'Catering premium',
      introTitle: 'Una mesa que se siente abundante desde que llega.',
      introCopy: 'Disenamos pedidos para grupos con los platos que ya cargan la identidad de Al Carbon: pollo, fajita, parrilladas, arroz, frijoles charros, tortillas y salsas.',
      packages: [
        {
          title: 'Pollo al carbon',
          kicker: 'Firma de la casa',
          desc: 'Pollos enteros o medios pollos con arroz, tortillas, chile toreado, cebolla asada y salsas.',
          detail: 'Perfecto para grupos familiares y reuniones de oficina.',
        },
        {
          title: 'Parrilladas',
          kicker: 'Para compartir',
          desc: 'Fajita, pollo, salchicha, charro beans, ensalada, tortillas y salsas con porciones generosas.',
          detail: 'La opcion mas completa para mesas grandes.',
        },
        {
          title: 'Fajita y sides',
          kicker: 'Plan a la medida',
          desc: 'Arma el volumen del evento con fajita de res, arroz, frijoles charros, bebidas y extras.',
          detail: 'Ideal cuando necesitas control de porciones.',
        },
      ],
      processEyebrow: 'Proceso',
      processTitle: 'Del primer mensaje al ultimo taco.',
      processCopy: 'El formulario deja todo organizado para que el equipo pueda responder con contexto: fecha, volumen, sucursal, presupuesto y notas importantes.',
      steps: [
        { title: 'Cuentanos el evento', desc: 'Fecha, horario, numero de invitados, sucursal ideal y estilo de servicio.' },
        { title: 'Coordinamos el pedido', desc: 'El equipo revisa cantidades, tiempos y disponibilidad para darte una propuesta clara.' },
        { title: 'Sale caliente', desc: 'Tu orden se prepara con el mismo fuego de la casa y lista para tu celebracion.' },
      ],
      requestEyebrow: 'Solicitud',
      requestTitle: 'Cuentanos que estas planeando.',
      requestCopy: 'El pedido llega preparado al correo oficial del sitio. Para contacto directo, escribe a',
      hoursLabel: 'Horario',
      coverageLabel: 'Cobertura',
      coverage: '5 ubicaciones en San Antonio',
      everyDay: 'todos los dias',
      locationEyebrow: 'Sucursales',
      locationTitle: 'Elige el punto mas conveniente.',
      viewMap: 'Ver mapa',
      form: {
        name: 'Nombre',
        email: 'Email',
        phone: 'Telefono',
        company: 'Empresa u organizacion',
        date: 'Fecha',
        time: 'Hora',
        guests: 'Invitados',
        eventType: 'Tipo de evento',
        location: 'Sucursal preferida',
        service: 'Servicio',
        budget: 'Presupuesto estimado',
        notes: 'Detalles del evento',
        namePlaceholder: 'Tu nombre',
        emailPlaceholder: 'tu@email.com',
        companyPlaceholder: 'Opcional',
        datePlaceholder: 'Selecciona fecha',
        notesPlaceholder: 'Cuentanos el lugar, horario, comida que tienes en mente, necesidades especiales y cualquier detalle importante.',
        selectLabel: 'Selecciona',
        today: 'Hoy',
        submit: 'Enviar solicitud',
        dateError: 'Selecciona la fecha del evento.',
        emptyGuests: 'Comparte invitados para estimar volumen.',
        compact: 'Formato compacto: pollo, sides y extras clave.',
        event: 'Formato evento: parrilladas, sides y bebidas por volumen.',
        large: 'Formato grande: coordinacion especial y pickup por horario.',
        sent: 'Se abrio tu aplicacion de correo con la solicitud dirigida a {{email}}.',
        help: 'El formulario abre un email dirigido a {{email}} con todos los detalles listos para enviar.',
      },
      eventTypes: {
        family: 'Reunion familiar',
        office: 'Comida de oficina',
        birthday: 'Cumpleanos',
        graduation: 'Graduacion',
        corporate: 'Evento corporativo',
        wedding: 'Boda o ensayo',
        other: 'Otro',
      },
      serviceStyles: {
        pickup: 'Pickup en sucursal',
        largeOrder: 'Coordinacion de orden grande',
        guidance: 'Necesito orientacion',
      },
    },
    ordering: {
      eyebrow: 'Ordena Al Carbon',
      title: 'Tu pedido, sin perder el ritual de la brasa.',
      copy: 'El sitio debe sentirse tan directo como el servicio: eliges, confirmas y recibes comida caliente con el caracter de Monterrey.',
      figureAlt: 'Pollo al carbon sobre la parrilla',
      figureLabel: 'Pollo al carbon',
      figureCopy: 'La brasa en primer plano: piel dorada, fuego alto y ese acabado regio que sostiene toda la experiencia.',
      steps: [
        {
          kicker: 'Elige',
          title: 'Carta directa',
          desc: 'Pollo entero, medio pollo, parrilladas, burgers y postres organizados para decidir rapido sin perder apetito.',
          meta: 'Menu visual',
        },
        {
          kicker: 'Confirma',
          title: 'Pago claro',
          desc: 'Agrega tu orden, revisa el total y confirma pickup o delivery desde el celular con un flujo sencillo.',
          meta: 'Checkout agil',
        },
        {
          kicker: 'Recibe',
          title: 'Sale caliente',
          desc: 'Pasa por tu pedido o pidelo a domicilio. La experiencia conserva el foco en comida recien salida de la parrilla.',
          meta: 'Pickup y delivery',
        },
      ],
      facts: [
        { value: '5', label: 'ubicaciones en San Antonio' },
        { value: '11AM - 9PM', label: 'abierto todos los dias' },
        { value: 'Drive Thru', label: 'activo en Culebra 1 y Marbach' },
        { value: 'Uber Eats + DoorDash + Grubhub', label: 'delivery en 5 sucursales' },
      ],
    },
    why: {
      eyebrow: 'Por Que Al Carbon',
      title: 'Una cocina de brasa con pulso de ciudad.',
      copy: 'Cada plato pone el producto al frente: pollo al carbon, cortes a la parrilla y una operacion pensada para moverse por San Antonio.',
      imageAlt: 'Pollo al carbon en caja premium con brasa y humo',
      showcaseEyebrow: 'Mesa nortena',
      showcaseTitle: 'Hecho para ordenar rapido y comer en serio.',
      showcaseCopy: 'Cada orden mantiene el mismo ritmo: fuego alto, porciones generosas y una carta que se entiende desde el primer antojo.',
      stats: [
        { value: '8', label: 'piezas en el Pollo Entero' },
        { value: '16', label: 'tortillas en la parrillada familiar' },
        { value: '5', label: 'sucursales activas' },
        { value: '2', label: 'salsas para rematar' },
      ],
      values: [
        {
          title: 'Carbon de verdad',
          desc: 'La firma de la casa vive en la piel dorada, el chile toreado, la cebolla asada y el aroma de la parrilla.',
        },
        {
          title: 'Origen regio',
          desc: 'Parrilladas, salchicha especial, Monterrey Burger y Papa Nortena mantienen vivo el antojo del norte.',
        },
        {
          title: 'Servicio rapido',
          desc: 'Pickup, drive thru en Culebra 1 y Marbach y delivery en apps para resolver la comida sin sacrificar sabor.',
        },
        {
          title: 'Cinco puntos',
          desc: 'Culebra, Nacogdoches, Alamo Ranch y Marbach acercan la brasa a distintas zonas de San Antonio.',
        },
      ],
    },
    locations: {
      eyebrow: 'Ubicaciones reales',
      title: 'San Antonio sabe donde caerle.',
      copy: 'Selecciona una sucursal en el mapa o en las cards para ubicarla y abrir la ruta exacta.',
      active: 'Sucursal activa',
      openMaps: 'Abrir en Maps',
      branch: 'Sucursal',
      hours: 'Horario',
      orderNow: 'Ordenar ahora',
      mapsAria: 'Abrir {{location}} en Google Maps',
      unavailable: 'Mapa no disponible',
      unavailableCopy: 'Usa los botones de Maps en cada sucursal para abrir la ubicacion exacta.',
      tags: {
        uberEats: 'Uber Eats',
        doorDash: 'DoorDash',
        pickup: 'Pickup',
        driveThru: 'Drive Thru',
        callIn: 'Pedidos por telefono',
      },
      notes: {
        alamoRanch: 'Uno de los puntos mas fuertes para pedidos al oeste.',
        culebra1: 'La sucursal con drive thru para salir rapido.',
        culebra2: 'Ideal para pedidos por telefono y pickup directo.',
        nacogdoches: 'Cobertura comoda para pickup y delivery.',
        marbach: 'Nuevo punto para pedidos al oeste y zona Marbach.',
      },
    },
    footer: {
      ctaTitle: 'Listo para caerle a Al Carbon?',
      ctaCopy: 'Abierto diario {{hours}} en 5 ubicaciones de San Antonio.',
      description: 'Pollo al carbon, parrilladas y burgers con 5 puntos activos en San Antonio. Marca real, fuego real, servicio real.',
      navTitle: 'Navegacion',
      locationsTitle: 'Sucursales',
      contactTitle: 'Contacto y ordenes',
      locationCopy: '5 ubicaciones activas en San Antonio, incluyendo Culebra, Nacogdoches, Alamo Ranch y Marbach.',
      allLocations: 'Ver todas las ubicaciones',
      dailyHours: 'Horario diario',
      rights: 'Todos los derechos reservados.',
      made: 'Hecho para San Antonio con fuego, pollo y mucho antojo.',
    },
    deliveryFlow: {
      title: 'Pide tu delivery',
      subtitle: 'Dinos tu direccion y te llevamos directo a la app de tu sucursal mas cercana.',
      addressLabel: 'Tu direccion de entrega',
      addressPlaceholder: 'Calle y numero, ciudad...',
      searching: 'Buscando direcciones...',
      noResults: 'Sin resultados. Intenta con otra direccion.',
      useLocation: 'Usar mi ubicacion actual',
      locating: 'Localizandote...',
      geoError: 'No pudimos obtener tu ubicacion. Escribe tu direccion o elige una sucursal.',
      orPick: 'O elige tu sucursal',
      manualHint: 'Selecciona la sucursal mas cercana a ti',
      poweredByGoogle: 'Direcciones por Google',
      keyMissing: 'La busqueda de direcciones se activa con tu llave de Google Maps. Mientras, usa tu ubicacion o elige una sucursal.',
      nearestEyebrow: 'Tu sucursal mas cercana',
      deliveringTo: 'Entregando a',
      away: 'a {{distance}} de ti',
      orderPrompt: 'Pidela en:',
      orderOn: 'Pedir en {{platform}}',
      noPlatforms: 'Esta sucursal aun no esta en apps de delivery. Llamala directo:',
      call: 'Llamar',
      changeAddress: 'Cambiar direccion',
      otherBranches: 'Ver otras sucursales',
      hideBranches: 'Ocultar otras sucursales',
      close: 'Cerrar',
    },
  },
  en: {
    nav: {
      home: 'Home',
      menu: 'Menu',
      order: 'Order',
      catering: 'Catering',
      locations: 'Locations',
      contact: 'Contact',
    },
    common: {
      order: 'Order',
      pickup: 'Order Pickup',
      delivery: 'Order Delivery',
      viewLocations: 'View locations',
      emailTeam: 'Email the team',
      directEmail: 'Direct email',
      locations: 'Locations',
      allDay: 'Every day',
      signature: 'Signature',
      closePromo: 'Close promotion',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      previousMonth: 'Previous month',
      nextMonth: 'Next month',
    },
    promo: {
      lead: '5 locations in San Antonio',
      text: 'Open daily {{hours}} · Pickup and delivery',
    },
    hero: {
      eyebrow: 'The Originals from Monterrey',
      subtitle: 'Pollos Asados',
      copy: 'Charcoal-grilled chicken, parrilladas, and northern Mexican cravings served with the intensity of the fire. Five San Antonio locations ready for pickup or delivery.',
      hoursLabel: 'Every day',
      driveLabel: 'Culebra 1 and Marbach',
      signatureTitle: 'Whole Chicken',
      signatureDesc: '8 pieces with rice, grilled onion, chile toreado, lime, tortillas, red salsa, and green salsa.',
    },
    menu: {
      eyebrow: 'House Menu',
      title: 'The fire leads the plate',
      copy: 'Charcoal-grilled chicken, grilled cuts, shareable parrilladas, and homemade desserts in a clear, direct menu.',
      featured: 'House favorites',
      dishes: 'dishes',
      official: 'Official Al Carbon menu',
      officialShort: 'Official menu',
      viewFull: 'View full menu',
      categories: {
        all: 'Featured',
        chicken: 'Chicken',
        beef: 'Beef',
        parrilladas: 'Parrilladas',
        burgers: 'Burgers',
        desserts: 'Desserts',
        drinks: 'Drinks',
        extras: 'Extras',
        papaNortena: 'Papa Nortena',
        cannedSodas: 'Canned Sodas',
      },
      badges: {
        mostPopular: 'Most Popular',
        fanFavorite: 'Fan Favorite',
        bestSeller: 'Best Seller',
        bestValue: 'Best Value',
        signature: 'Signature',
        forTwo: 'For 2',
        mustTry: 'Must Try',
      },
      items: {
        1: {
          name: 'Whole Chicken',
          desc: '8 pieces of charcoal-grilled chicken with rice, grilled onion, chile toreado, lime, corn tortillas, green salsa, and red salsa.',
        },
        2: {
          name: 'Half Chicken',
          desc: '4 pieces of charcoal-grilled chicken with rice, grilled onion, chile toreado, lime, corn tortillas, green salsa, and red salsa.',
        },
        3: {
          name: 'Whole Chicken Only',
          desc: '8 pieces of charcoal-grilled chicken with no sides. Just the chicken.',
        },
        4: {
          name: 'Half Chicken Only',
          desc: '4 pieces of charcoal-grilled chicken with no sides. Just the chicken.',
        },
        5: {
          name: '1 lb Beef Fajita',
          desc: '1 lb grilled beef fajita with 12 oz rice, grilled onions and peppers, chile toreado, salad, tortillas, lime, and salsas.',
        },
        6: {
          name: '1/2 lb Beef Fajita',
          desc: '1/2 lb grilled beef fajita with 8 oz rice, grilled onions and peppers, chile toreado, salad, tortillas, lime, and salsas.',
        },
        7: {
          name: '1 lb Short Ribs',
          desc: '1 lb grilled short ribs with 12 oz rice, grilled onions and peppers, chile toreado, salad, tortillas, lime, and salsas.',
        },
        8: {
          name: '1/2 lb Short Ribs',
          desc: '1/2 lb grilled short ribs with 8 oz rice, grilled onions and peppers, chile toreado, salad, tortillas, lime, and salsas.',
        },
        9: {
          name: 'Parrillada Para Dos',
          desc: '1/2 lb fajita, 1/2 chicken, rice, charro beans, salad, chile toreado, special sausage, 8 tortillas, and salsas. Made for 2.',
        },
        10: {
          name: 'Parrillada Familiar',
          desc: '1 lb fajita, 1 whole chicken, 2 rice sides, 2 charro beans, 2 salads, 2 chiles toreados, 2 sausages, 16 tortillas, and salsas. Made for the family.',
        },
        11: {
          name: 'Classic Hamburger',
          desc: '1/2 lb Angus beef patty with American cheese, pickles, mustard, mayo, lettuce, and tomato. Served with Lays Classic chips.',
        },
        12: {
          name: 'Monterrey Burger',
          desc: '1/2 lb Angus beef with ham, Monterrey Jack cheese, chile toreado, chipotle, grilled onion, guacamole, lettuce, and tomato. Served with chips.',
        },
        13: {
          name: 'Salchiburger',
          desc: '1/2 lb Angus beef with ham, sausage, Monterrey Jack cheese, grilled onion, guacamole, lettuce, and tomato. Served with chips.',
        },
        14: {
          name: 'Tres Leches Cake',
          desc: 'Classic tres leches cake, soft and creamy, topped with whipped cream.',
        },
        15: {
          name: 'Arroz con Leche',
          desc: 'Creamy rice pudding with cinnamon. A comforting house dessert.',
        },
        16: {
          name: '32 oz Drink',
          desc: '32 oz drink of your choice: soda, lemonade, or aguas frescas.',
        },
        17: {
          name: '16 oz Drink',
          desc: '16 oz drink of your choice: soda, lemonade, or aguas frescas.',
        },
        18: {
          name: 'Papa Nortena',
          desc: 'Loaded baked potato with cream, butter, Monterrey Jack and cheddar cheese sauce, bacon, grilled beef, crackers, and jalapenos.',
        },
        19: {
          name: '12 oz Charro Beans',
          desc: 'House charro beans, rich and brothy. The perfect side for your plate.',
        },
        20: {
          name: '32 oz Charro Beans',
          desc: 'Family-size charro beans, ideal for sharing with the table.',
        },
        21: {
          name: 'Grilled Sausage',
          desc: 'Special charcoal-grilled sausage. The authentic extra that rounds out any plate.',
        },
        22: {
          name: 'Chocoflan',
          desc: 'An irresistible mix of chocolate cake and vanilla flan. Creamy, moist, and full of flavor.',
        },
        23: {
          name: 'Cheese Flan',
          desc: 'Smooth cream cheese flan covered in caramel. Creamy texture with a sweet, irresistible finish.',
        },
        24: {
          name: 'Strawberry Cheesecake',
          desc: 'Classic cheesecake with a cookie crust, creamy filling, and fresh strawberry topping.',
        },
        25: {
          name: '12 oz Canned Soda',
          desc: '12 oz canned soda: Coke, Sprite, Dr Pepper, and more. The perfect complement to your plate.',
        },
      },
    },
    liveMenu: {
      eyebrow: 'Live menu',
      title: 'Menu by location',
      copy: 'Dishes and prices synced straight from each location’s system. Pick your spot and see what’s on today.',
      branch: 'Location',
      orderNow: 'Order now',
      error: 'We could not load the menu for this location. Please try again.',
      retry: 'Retry',
      synced: 'Prices synced live with each location',
    },
    cart: {
      title: 'Your order',
      add: 'Add',
      options: 'With options',
      item: 'item',
      items: 'items',
      view: 'View order',
      empty: 'Your order is empty.',
      subtotal: 'Subtotal',
      taxNote: 'Taxes and tip are calculated at payment.',
      name: 'Full name',
      email: 'Email',
      phone: 'Phone (optional)',
      checkout: 'Pay with Clover',
      processing: 'Connecting to Clover...',
      error: 'Could not start the payment. Please try again.',
      emailInvalid: 'Check your email — it looks incomplete or invalid.',
      customize: 'Choose options',
      addToOrder: 'Add to order',
      chooseOne: 'Choose 1',
      chooseAtLeast: 'Choose at least {{n}}',
      chooseUpTo: 'Choose up to {{n}}',
      optional: 'Optional',
      secure: 'Secure payment processed by Clover.',
    },
    cateringCta: {
      eyebrow: 'Al Carbon Catering',
      title: 'Bring the fire to your event.',
      copy: 'Family gatherings, office lunches, celebrations, and large events with the Al Carbon flavor, coordinated from our San Antonio locations.',
      quote: 'Request catering',
      ideal: 'Ideal for',
      points: ['Group parrilladas', 'Charcoal chicken by volume', 'Sides, salsas, and tortillas'],
      note: 'Complete the request and our team receives every event detail through the official site email.',
    },
    catering: {
      title: 'Al Carbon Catering | Events and Parrilladas in San Antonio',
      meta: 'Al Carbon Pollos Asados catering for events in San Antonio. Request charcoal chicken, parrilladas, fajita, sides, and group coordination.',
      heroEyebrow: 'Catering request',
      heroSubtitle: 'Al Carbon',
      heroCopy: 'Planning an event? Let us handle the food with charcoal chicken, parrilladas, fajita, sides, and the fire-grilled flavor San Antonio already knows.',
      heroAlt: 'Al Carbon family parrillada for catering',
      quote: 'Request a quote',
      statsEyebrow: 'Events with real fire',
      branches: 'Locations',
      daily: 'Daily',
      fire: 'Fire',
      regional: 'Monterrey',
      introEyebrow: 'Premium catering',
      introTitle: 'A table that feels generous the moment it arrives.',
      introCopy: 'We build group orders around the plates that carry Al Carbon’s identity: chicken, fajita, parrilladas, rice, charro beans, tortillas, and salsas.',
      packages: [
        {
          title: 'Charcoal chicken',
          kicker: 'House signature',
          desc: 'Whole or half chickens with rice, tortillas, chile toreado, grilled onion, and salsas.',
          detail: 'Perfect for family gatherings and office meals.',
        },
        {
          title: 'Parrilladas',
          kicker: 'Made to share',
          desc: 'Fajita, chicken, sausage, charro beans, salad, tortillas, and salsas with generous portions.',
          detail: 'The most complete option for bigger tables.',
        },
        {
          title: 'Fajita and sides',
          kicker: 'Built to fit',
          desc: 'Plan your event volume with beef fajita, rice, charro beans, drinks, and extras.',
          detail: 'Ideal when you need portion control.',
        },
      ],
      processEyebrow: 'Process',
      processTitle: 'From the first message to the last taco.',
      processCopy: 'The form organizes everything our team needs to respond with context: date, volume, preferred location, budget, and important notes.',
      steps: [
        { title: 'Tell us about the event', desc: 'Date, time, guest count, preferred location, and service style.' },
        { title: 'We coordinate the order', desc: 'The team reviews quantities, timing, and availability to provide a clear plan.' },
        { title: 'It leaves hot', desc: 'Your order is prepared with the same house fire and ready for your celebration.' },
      ],
      requestEyebrow: 'Request',
      requestTitle: 'Tell us what you are planning.',
      requestCopy: 'Your request is prepared for the official site email. For direct contact, write to',
      hoursLabel: 'Hours',
      coverageLabel: 'Coverage',
      coverage: '5 locations in San Antonio',
      everyDay: 'every day',
      locationEyebrow: 'Locations',
      locationTitle: 'Choose the most convenient location.',
      viewMap: 'View map',
      form: {
        name: 'Name',
        email: 'Email',
        phone: 'Phone',
        company: 'Company or organization',
        date: 'Date',
        time: 'Time',
        guests: 'Guests',
        eventType: 'Event type',
        location: 'Preferred location',
        service: 'Service',
        budget: 'Estimated budget',
        notes: 'Event details',
        namePlaceholder: 'Your name',
        emailPlaceholder: 'you@email.com',
        companyPlaceholder: 'Optional',
        datePlaceholder: 'Select date',
        notesPlaceholder: 'Tell us the venue, timing, food you have in mind, special needs, and any important details.',
        selectLabel: 'Select',
        today: 'Today',
        submit: 'Send request',
        dateError: 'Select the event date.',
        emptyGuests: 'Add guest count to estimate volume.',
        compact: 'Compact format: chicken, sides, and key extras.',
        event: 'Event format: parrilladas, sides, and drinks by volume.',
        large: 'Large format: special coordination and scheduled pickup.',
        sent: 'Your email app opened with the request addressed to {{email}}.',
        help: 'The form opens an email addressed to {{email}} with every detail ready to send.',
      },
      eventTypes: {
        family: 'Family gathering',
        office: 'Office lunch',
        birthday: 'Birthday',
        graduation: 'Graduation',
        corporate: 'Corporate event',
        wedding: 'Wedding or rehearsal',
        other: 'Other',
      },
      serviceStyles: {
        pickup: 'Pickup from location',
        largeOrder: 'Large order coordination',
        guidance: 'Need guidance',
      },
    },
    ordering: {
      eyebrow: 'Order Al Carbon',
      title: 'Your order, without losing the ritual of the fire.',
      copy: 'The experience should feel as direct as the service: choose, confirm, and receive hot food with the character of Monterrey.',
      figureAlt: 'Charcoal chicken on the grill',
      figureLabel: 'Charcoal chicken',
      figureCopy: 'The fire up front: golden skin, high heat, and the Monterrey-style finish that anchors the whole experience.',
      steps: [
        {
          kicker: 'Choose',
          title: 'Direct menu',
          desc: 'Whole chicken, half chicken, parrilladas, burgers, and desserts organized so you can decide fast without losing your appetite.',
          meta: 'Visual menu',
        },
        {
          kicker: 'Confirm',
          title: 'Clear payment',
          desc: 'Add your order, review the total, and confirm pickup or delivery from your phone with a simple flow.',
          meta: 'Easy checkout',
        },
        {
          kicker: 'Receive',
          title: 'Leaves hot',
          desc: 'Pick up your order or get it delivered. The experience stays focused on food fresh from the grill.',
          meta: 'Pickup and delivery',
        },
      ],
      facts: [
        { value: '5', label: 'locations in San Antonio' },
        { value: '11AM - 9PM', label: 'open every day' },
        { value: 'Drive Thru', label: 'active at Culebra 1 and Marbach' },
        { value: 'Uber Eats + DoorDash + Grubhub', label: 'delivery from 5 locations' },
      ],
    },
    why: {
      eyebrow: 'Why Al Carbon',
      title: 'A fire-grilled kitchen with city rhythm.',
      copy: 'Every plate puts the product first: charcoal chicken, grilled cuts, and an operation built to move across San Antonio.',
      imageAlt: 'Charcoal chicken in a premium box with fire and smoke',
      showcaseEyebrow: 'Northern table',
      showcaseTitle: 'Made to order fast and eat seriously.',
      showcaseCopy: 'Every order keeps the same rhythm: high heat, generous portions, and a menu that makes sense from the first craving.',
      stats: [
        { value: '8', label: 'pieces in the Whole Chicken' },
        { value: '16', label: 'tortillas in the family parrillada' },
        { value: '5', label: 'active locations' },
        { value: '2', label: 'salsas to finish' },
      ],
      values: [
        {
          title: 'Real charcoal',
          desc: 'The house signature lives in the golden skin, chile toreado, grilled onion, and the aroma of the grill.',
        },
        {
          title: 'Monterrey roots',
          desc: 'Parrilladas, special sausage, Monterrey Burger, and Papa Nortena keep the northern craving alive.',
        },
        {
          title: 'Fast service',
          desc: 'Pickup, drive thru at Culebra 1 and Marbach, and app delivery solve the meal without sacrificing flavor.',
        },
        {
          title: 'Five locations',
          desc: 'Culebra, Nacogdoches, Alamo Ranch, and Marbach bring the fire closer to different areas of San Antonio.',
        },
      ],
    },
    locations: {
      eyebrow: 'Real locations',
      title: 'San Antonio knows where to pull up.',
      copy: 'Select a location on the map or cards to find it and open the exact route.',
      active: 'Active location',
      openMaps: 'Open in Maps',
      branch: 'Location',
      hours: 'Hours',
      orderNow: 'Order now',
      mapsAria: 'Open {{location}} in Google Maps',
      unavailable: 'Map unavailable',
      unavailableCopy: 'Use the Maps buttons on each location to open the exact address.',
      tags: {
        uberEats: 'Uber Eats',
        doorDash: 'DoorDash',
        pickup: 'Pickup',
        driveThru: 'Drive Thru',
        callIn: 'Call-in orders',
      },
      notes: {
        alamoRanch: 'One of the strongest west-side locations for orders.',
        culebra1: 'The drive-thru location built for quick pickup.',
        culebra2: 'Ideal for phone orders and direct pickup.',
        nacogdoches: 'Convenient coverage for pickup and delivery.',
        marbach: 'A newer spot for west-side and Marbach-area orders.',
      },
    },
    footer: {
      ctaTitle: 'Ready for Al Carbon?',
      ctaCopy: 'Open daily {{hours}} across 5 San Antonio locations.',
      description: 'Charcoal chicken, parrilladas, and burgers with 5 active locations in San Antonio. Real brand, real fire, real service.',
      navTitle: 'Navigation',
      locationsTitle: 'Locations',
      contactTitle: 'Contact and orders',
      locationCopy: '5 active locations in San Antonio, including Culebra, Nacogdoches, Alamo Ranch, and Marbach.',
      allLocations: 'View all locations',
      dailyHours: 'Daily hours',
      rights: 'All rights reserved.',
      made: 'Made for San Antonio with fire, chicken, and serious cravings.',
    },
    deliveryFlow: {
      title: 'Get it delivered',
      subtitle: 'Tell us your address and we’ll take you straight to your nearest location’s app.',
      addressLabel: 'Your delivery address',
      addressPlaceholder: 'Street and number, city...',
      searching: 'Searching addresses...',
      noResults: 'No matches. Try another address.',
      useLocation: 'Use my current location',
      locating: 'Locating you...',
      geoError: 'We couldn’t get your location. Type your address or pick a location.',
      orPick: 'Or choose a location',
      manualHint: 'Select the location closest to you',
      poweredByGoogle: 'Addresses by Google',
      keyMissing: 'Address search turns on with your Google Maps key. Meanwhile, use your location or pick a location.',
      nearestEyebrow: 'Your nearest location',
      deliveringTo: 'Delivering to',
      away: '{{distance}} away',
      orderPrompt: 'Order it on:',
      orderOn: 'Order on {{platform}}',
      noPlatforms: 'This location isn’t on delivery apps yet. Call it directly:',
      call: 'Call',
      changeAddress: 'Change address',
      otherBranches: 'See other locations',
      hideBranches: 'Hide other locations',
      close: 'Close',
    },
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    return window.localStorage.getItem('al-carbon-language') || 'en';
  });

  const setLanguage = (nextLanguage) => {
    setLanguageState(nextLanguage);
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('al-carbon-language', nextLanguage);
    }
  };

  useEffect(() => {
    document.documentElement.lang = language === 'en' ? 'en' : 'es';
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: TRANSLATIONS[language],
  }), [language]);

  return createElement(LanguageContext.Provider, { value }, children);
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }

  return context;
}

export function interpolate(template, values) {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{{${key}}}`, value),
    template,
  );
}
